### ISSUE TITLE
Create all users in one block instead of 3

### ISSUE THREAD

**Issue by lowks** [censof/saga-8.2-installation#2]
This: 

```
- name: Create acct user
  user: name=acct
- name: Create fourjs user
  user: name=fourjs
- name: Create informix user
user: name=informix
```

can be summarized into

```
- name: Create users
   user: name={{ item }} state=present
   with_items:
      - acct
      - fourjs
      - informix
```
Please learn to use `with_items` to make your playbooks more concise.
