### ISSUE TITLE
Group creation can be summarized

### ISSUE THREAD

**Issue by lowks** [censof/saga-8.2-installation#3]
This:

```

- group:
    name: acct
    state: present
    
- group:
    name: fourjs
    state: present
```

can be summarized into

```
- group:
   name: {{ item }}
   state: present
   with_items:
      - fourjs
      - acct
```
