### ISSUE TITLE
check if owner and user can used with unarchive module

### ISSUE THREAD

**Issue by lowks** [censof/saga-8.2-installation#9]
Based on this: https://github.com/ansible/ansible-modules-core/issues/234

The `owner` and `group` can already be passed to the `unarchive` module for Ansible. This means that if this is possible (for 2.0.0.2 - the one we are using), then this: 

```
- name: Create Project
  unarchive: src=files/Projects.tar
             dest=/etc
  
- name: Projects chown to acct
  command: chown -R acct:acct Projects
  args:
       chdir: /etc
ignore_errors: yes
```

can be made into:

```
- name: Create Project
  unarchive: src=files/Projects.tar
             dest=/etc
             owner=acct
             group=acct
```

Please test and if possible use the shorter syntax.
